debugMode: false
addons:
  placeholdersAPI: true
  holograms: false
  holographicdisplays: true
mainLobby: null
redPanelInLocked: true
progressBarAmount: 10
excluideDefKits: true
kitLevelsOrder: true
lobbyScoreboard: true
updatePlayersPlaceholder: 5
effectsOnKill:
  - "REGENERATION:2:5"
redPanel:
  material: STAINED_GLASS_PANE
  data: 14
breakMap:
  enabled: true
  bypass:
    - GRASS
    - STONE
flagDefaults:
  hunger: true
  gracePeriod: 60
  phases:
    PHASE_I:
      type: PHASE_I
      time: 60
      pickaxe: WOOD_PICKAXE
      enchants:
        - DIG_SPEED:1:true
        - DURABILITY:1:true
    PHASE_II:
      type: PHASE_II
      time: 120
      pickaxe: STONE_PICKAXE
      enchants:
        - DIG_SPEED:1:true
        - DURABILITY:1:true
    PHASE_III:
      type: PHASE_III
      time: 180
      pickaxe: IRON_PICKAXE
      enchants:
        - DIG_SPEED:1:true
        - DURABILITY:1:true
    PHASE_IV:
      type: PHASE_IV
      time: 240
      pickaxe: DIAMOND_PICKAXE
      enchants:
        - DIG_SPEED:1:true
        - DURABILITY:1:true
gameDefaults:
  hunger: true
  maxMultiplier: 5
  starting: 30
  timeToKill: 30
  limitOfYSpawn: 30
  gcoins:
    kill: 3
    win: 10
    assists: 1
  coins:
    kill: 5
    win: 20
    assists: 2
  xp:
    kill: 5
    win: 10
    assists: 2
  noDrop:
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
    - ARROW
    - GOLDEN_APPLE
    - STAINED_CLAY
bounty:
  min: 90
  max: 110
  perKill: 0.10
items:
  lobby:
    enabled: true
    slot: 2
    cmd: /ctw lobby
materials:
  lobby: DIAMOND
  closeitem: BOOK