name: UltraCaptureTheWool
main: io.github.Leonardo0013YT.UltraCTW.Main
version: 1.9.9
author: Leonardo0013YT
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI]
depend: [NametagEdit, ProtocolLib, WorldEdit, FastAsyncWorldEdit]
commands:
  ctws:
  ctw:
    aliases: [ultractw]