debugMode: false
addons:
  placeholdersAPI: true
  holograms: false
  holographicdisplays: true
mainLobby: null
redPanelInLocked: true
progressBarAmount: 10
redPanel:
  material: STAINED_GLASS_PANE
  data: 14
gameDefaults:
  maxMultiplier: 5
  starting: 30
  timeToKill: 30
  gcoins:
    kill: 3
    win: 10
    assists: 1
  coins:
    kill: 5
    win: 20
    assists: 2
  xp:
    kill: 5
    win: 10
    assists: 2
bounty:
  min: 90
  max: 110
  perKill: 0.10
materials:
  lobby: DIAMOND
  closeitem: BOOK