debugMode: false
addons:
  placeholdersAPI: true
mainLobby: null
redPanelInLocked: true
redPanel:
  material: STAINED_GLASS_PANE
  data: 14
gameDefaults:
  starting: 30
materials:
  lobby: DIAMOND
  closeitem: BOOK