name: UltraCaptureTheWool
main: io.github.Leonardo0013YT.UltraCTW.UltraCTW
version: 2.1.0
author: Leonardo0013YT
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI]
depend: [NametagEdit, ProtocolLib, WorldEdit, FastAsyncWorldEdit]
commands:
  ctws:
    aliases: [ultractws]
  ctw:
    aliases: [ultractw]